import type { Metadata } from "next";
import { Roboto, Noto_Serif_JP } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import ThemeToggle from '@/components/common/ThemeToggle';
import Nav from "@/components/ui/navigation";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

const notoSerifJP = Noto_Serif_JP({
  variable: "--font-noto-serif-jp",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by Vercel AI SDK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${notoSerifJP.variable} ${roboto.variable} bg-linear-to-br from-stone-50 to-stone-200 dark:from-stone-800 dark:to-stone-950 antialiased`}
      >
        <Nav />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          {children}
          <ThemeToggle className="fixed top-2 left-2" />
        </ThemeProvider>
      </body>
    </html>
  );
}
